In [1]:
import pandas as pd
df = pd.read_csv("diabetic_data (1).csv")

In [2]:
df.shape

(101766, 50)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   encounter_id              101766 non-null  int64 
 1   patient_nbr               101766 non-null  int64 
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64 
 7   discharge_disposition_id  101766 non-null  int64 
 8   admission_source_id       101766 non-null  int64 
 9   time_in_hospital          101766 non-null  int64 
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64 
 13  num_procedures            101766 non-null  int64 
 14  num_

In [4]:
df.describe()

encounter_id   patient_nbr  admission_type_id  \
count  1.017660e+05  1.017660e+05      101766.000000   
mean   1.652016e+08  5.433040e+07           2.024006   
std    1.026403e+08  3.869636e+07           1.445403   
min    1.252200e+04  1.350000e+02           1.000000   
25%    8.496119e+07  2.341322e+07           1.000000   
50%    1.523890e+08  4.550514e+07           1.000000   
75%    2.302709e+08  8.754595e+07           3.000000   
max    4.438672e+08  1.895026e+08           8.000000   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
count             101766.000000        101766.000000     101766.000000   
mean                   3.715642             5.754437          4.395987   
std                    5.280166             4.064081          2.985108   
min                    1.000000             1.000000          1.000000   
25%                    1.000000             1.000000          2.000000   
50%                    1.000000             7.000000          4.000000   
75%                    4.000000             7.000000          6.000000   
max                   28.000000            25.000000         14.000000   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
count       101766.000000   101766.000000    101766.000000      101766.000000   
mean            43.095641        1.339730        16.021844           0.369357   
std             19.674362        1.705807         8.127566           1.267265   
min              1.000000        0.000000         1.000000           0.000000   
25%             31.000000        0.000000        10.000000           0.000000   
50%             44.000000        1.000000        15.000000           0.000000   
75%             57.000000        2.000000        20.000000           0.000000   
max            132.000000        6.000000        81.000000          42.000000   

       number_emergency  number_inpatient  number_diagnoses  
count     101766.000000     101766.000000     101766.000000  
mean           0.197836          0.635566          7.422607  
std            0.930472          1.262863          1.933600  
min            0.000000          0.000000          1.000000  
25%            0.000000          0.000000          6.000000  
50%            0.000000          0.000000          8.000000  
75%            0.000000          1.000000          9.000000  
max           76.000000         21.000000         16.000000

In [5]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [6]:
df.head()

encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?   
1        149190     55629189        Caucasian  Female  [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3        500364     82442376        Caucasian    Male  [30-40)      ?   
4         16680     42519267        Caucasian    Male  [40-50)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  

[5 rows x 50 columns]

In [7]:
print("Unique value in each feature")
for i in df.columns:
    print("df[",i,"]: " ,len(df[i].unique()))

Unique value in each feature
df[ encounter_id ]:  101766
df[ patient_nbr ]:  71518
df[ race ]:  6
df[ gender ]:  3
df[ age ]:  10
df[ weight ]:  10
df[ admission_type_id ]:  8
df[ discharge_disposition_id ]:  26
df[ admission_source_id ]:  17
df[ time_in_hospital ]:  14
df[ payer_code ]:  18
df[ medical_specialty ]:  73
df[ num_lab_procedures ]:  118
df[ num_procedures ]:  7
df[ num_medications ]:  75
df[ number_outpatient ]:  39
df[ number_emergency ]:  33
df[ number_inpatient ]:  21
df[ diag_1 ]:  717
df[ diag_2 ]:  749
df[ diag_3 ]:  790
df[ number_diagnoses ]:  16
df[ max_glu_serum ]:  4
df[ A1Cresult ]:  4
df[ metformin ]:  4
df[ repaglinide ]:  4
df[ nateglinide ]:  4
df[ chlorpropamide ]:  4
df[ glimepiride ]:  4
df[ acetohexamide ]:  2
df[ glipizide ]:  4
df[ glyburide ]:  4
df[ tolbutamide ]:  2
df[ pioglitazone ]:  4
df[ rosiglitazone ]:  4
df[ acarbose ]:  4
df[ miglitol ]:  4
df[ troglitazone ]:  2
df[ tolazamide ]:  3
df[ examide ]:  1
df[ citoglipton ]:  1
df[ insulin ]: 

In [8]:
# Check if there is any duplicates
duplicates=df.duplicated()
sum(duplicates)

0

In [9]:
object_columns = df.select_dtypes(include='object').columns.tolist()
numerical_columns = df.select_dtypes(include=['int','float']).columns.tolist()
print("Object Columns: ",object_columns)
print('\n')
print("Numerical columns: ",numerical_columns)

Object Columns:  ['race', 'gender', 'age', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']


Numerical columns:  ['encounter_id', 'patient_nbr', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']


In [10]:
for i in df.columns:
    n = df[i].unique()
    
    if len(n)<30:
        print(i)
        print(n)
    else:
        print(i + ': ' +str(len(n)) + ' unique values')

encounter_id: 101766 unique values
patient_nbr: 71518 unique values
race
['Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian' 'Hispanic']
gender
['Female' 'Male' 'Unknown/Invalid']
age
['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']
weight
['?' '[75-100)' '[50-75)' '[0-25)' '[100-125)' '[25-50)' '[125-150)'
 '[175-200)' '[150-175)' '>200']
admission_type_id
[6 1 2 3 4 5 8 7]
discharge_disposition_id
[25  1  3  6  2  5 11  7 10  4 14 18  8 13 12 16 17 22 23  9 20 15 24 28
 19 27]
admission_source_id
[ 1  7  2  4  5  6 20  3 17  8  9 14 10 22 11 25 13]
time_in_hospital
[ 1  3  2  4  5 13 12  9  7 10  6 11  8 14]
payer_code
['?' 'MC' 'MD' 'HM' 'UN' 'BC' 'SP' 'CP' 'SI' 'DM' 'CM' 'CH' 'PO' 'WC' 'OT'
 'OG' 'MP' 'FR']
medical_specialty: 73 unique values
num_lab_procedures: 118 unique values
num_procedures
[0 5 1 6 2 3 4]
num_medications: 75 unique values
number_outpatient: 39 unique values
number_emergency: 33 unique values
number_inpatient

Treating Missing values

In [11]:
import numpy as np
df.replace(to_replace="?",value=np.nan,inplace = True)

In [12]:
print(df.isna().sum())

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide 

Total 7 values have null values in them they are

In [15]:
print(df.columns[df.isna().sum() > 0])

Index(['race', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2',
       'diag_3'],
      dtype='object')


Explanation : These are the features having null values.

Finding the total percentage of null values for these columns

In [16]:
Features_to_impute = ['race', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2',
       'diag_3']
for i in Features_to_impute:
    print(i,":",(df[i].isna().sum()/len(df[i])*100))

race : 2.2335554114340743
weight : 96.85847925633315
payer_code : 39.5574160328597
medical_specialty : 49.08220820313268
diag_1 : 0.02063557573256294
diag_2 : 0.3517874339170253
diag_3 : 1.398305917497003


Droping the columns that have more than 39% of null values

In [17]:
df.drop(columns=['weight','payer_code','medical_specialty'],inplace=True)

In [18]:
df.shape

(101766, 47)

In [19]:
#Removing null values in gender column
df = df[df["gender"] != "Unknown/Invalid"]

In [20]:
df.shape

(101763, 47)

In [21]:
columns_to_check = ['race','diag_1','diag_2','diag_3']  # Replace with actual column names

# Remove rows with null values in the specified columns
df.dropna(subset=columns_to_check,inplace = True)

In [22]:
Features_to_impute = ['race', 'diag_1', 'diag_2',
       'diag_3']
for i in Features_to_impute:
    print(i,":",(df[i].isna().sum()/len(df[i])*100))

race : 0.0
diag_1 : 0.0
diag_2 : 0.0
diag_3 : 0.0


In [23]:
df.shape

(98052, 47)

In [24]:
df.drop(columns=['admission_type_id','discharge_disposition_id','admission_source_id'],inplace=True)

As these id's are not required for our analysis these id'd can be removed

In [25]:
df.shape

(98052, 44)

In [26]:
print(df.isna().sum())

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
time_in_hospital            0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide   

In [27]:
df.age.value_counts()

[70-80)     25305
[60-70)     21809
[80-90)     16702
[50-60)     16697
[40-50)      9265
[30-40)      3548
[90-100)     2717
[20-30)      1478
[10-20)       466
[0-10)         65
Name: age, dtype: int64

In [28]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Applying label encoding
df['age'] = label_encoder.fit_transform(df['age'])

In [29]:
df.age.value_counts()

7    25305
6    21809
8    16702
5    16697
4     9265
3     3548
9     2717
2     1478
1      466
0       65
Name: age, dtype: int64

Applying enconding for max_glu_serum , change & diabetesMed

In [30]:
def replace_data_to_binary(x,y):
    df.max_glu_serum.replace(x,y, inplace=True)
    df.change.replace(x,y, inplace=True)
    df.diabetesMed.replace(x,y, inplace=True)

replace_data_to_binary('None', 100)
replace_data_to_binary('Norm', 100)
replace_data_to_binary('>200', 200)
replace_data_to_binary('>300', 300)
replace_data_to_binary('No', -1)
replace_data_to_binary('Ch', 1)
replace_data_to_binary('Yes', 1)

In [31]:
# Review the data of max_glu_Serum, change, and diabetesMed after re-coding 
print('max_glu_serum :\n', df.max_glu_serum.value_counts())
print('change :\n', df.change.value_counts())
print('diabetesMed :\n', df.diabetesMed.value_counts())

max_glu_serum :
 100    95376
200     1449
300     1227
Name: max_glu_serum, dtype: int64
change :
 -1    52774
 1    45278
Name: change, dtype: int64
diabetesMed :
  1    75350
-1    22702
Name: diabetesMed, dtype: int64


Changing the variable 'readmitted' to binary type by clubbing the values ">30" and "<30" as "YES".

In [32]:
def replace_data_to_binary(x,y):
    df.readmitted.replace(x,y, inplace=True)

replace_data_to_binary('NO', 'NO')
replace_data_to_binary('>30','YES')
replace_data_to_binary('<30','YES')

In [33]:
print('readmitted :\n', df.readmitted.value_counts())

readmitted :
 NO     52337
YES    45715
Name: readmitted, dtype: int64


In [34]:
def replace_data_to_binary(x,y):
    df.A1Cresult.replace(x,y, inplace=True)

replace_data_to_binary('None', 0)
replace_data_to_binary('Norm',5)
replace_data_to_binary('>7',7)
replace_data_to_binary('>8',8)

In [35]:
print('A1Cresult :\n', df.A1Cresult.value_counts())

A1Cresult :
 0    81859
8     7631
5     4854
7     3708
Name: A1Cresult, dtype: int64


In [36]:
Features_of_medication = ['metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone']
def replace_data_to_binary(x,y):
    for i in Features_of_medication:
        df[i].replace(x,y, inplace=True)

replace_data_to_binary('Up', 10)
replace_data_to_binary('Down',-10)
replace_data_to_binary('Steady',0)
replace_data_to_binary('No',-20)

In [37]:
for i in Features_of_medication:
        print(i)
        print(df[i].value_counts())


metformin
-20    78807
 0     17677
 10     1017
-10      551
Name: metformin, dtype: int64
repaglinide
-20    96529
 0      1371
 10      107
-10       45
Name: repaglinide, dtype: int64
nateglinide
-20    97361
 0       657
 10       23
-10       11
Name: nateglinide, dtype: int64
chlorpropamide
-20    97969
 0        76
 10        6
-10        1
Name: chlorpropamide, dtype: int64
glimepiride
-20    93065
 0      4488
 10      315
-10      184
Name: glimepiride, dtype: int64
acetohexamide
-20    98051
 0         1
Name: acetohexamide, dtype: int64
glipizide
-20    85769
 0     10990
 10      752
-10      541
Name: glipizide, dtype: int64
glyburide
-20    87791
 0      8932
 10      791
-10      538
Name: glyburide, dtype: int64
tolbutamide
-20    98030
 0        22
Name: tolbutamide, dtype: int64
pioglitazone
-20    90955
 0      6755
 10      227
-10      115
Name: pioglitazone, dtype: int64
rosiglitazone
-20    91886
 0      5908
 10      174
-10       84
Name: rosiglitazone, dtype

In [38]:
df.shape

(98052, 44)

In [39]:
df.head()

encounter_id  patient_nbr             race  gender  age  time_in_hospital  \
1        149190     55629189        Caucasian  Female    1                 3   
2         64410     86047875  AfricanAmerican  Female    2                 2   
3        500364     82442376        Caucasian    Male    3                 2   
4         16680     42519267        Caucasian    Male    4                 1   
5         35754     82637451        Caucasian    Male    5                 3   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   
5                  31               6               16                  0   

   ...  citoglipton  insulin glyburide-metformin glipizide-metformin  \
1  ...          -20       10                 -20                 -20   
2  ...          -20      -20                 -20                 -20   
3  ...          -20       10                 -20                 -20   
4  ...          -20        0                 -20                 -20   
5  ...          -20        0                 -20                 -20   

  glimepiride-pioglitazone  metformin-rosiglitazone  metformin-pioglitazone  \
1                      -20                      -20                     -20   
2                      -20                      -20                     -20   
3                      -20                      -20                     -20   
4                      -20                      -20                     -20   
5                      -20                      -20                     -20   

   change  diabetesMed  readmitted  
1       1            1         YES  
2      -1            1          NO  
3       1            1          NO  
4       1            1          NO  
5      -1            1         YES  

[5 rows x 44 columns]

In [40]:
from sklearn.preprocessing import LabelEncoder

# Instantiate a LabelEncoder for each of the columns
label_encoder_race = LabelEncoder()
label_encoder_gender = LabelEncoder()
label_encoder_readmitted = LabelEncoder()

# Apply label encoding to each column
df['race'] = label_encoder_race.fit_transform(df["race"])
df["gender"] = label_encoder_gender.fit_transform(df["gender"])
df["readmitted"] = label_encoder_readmitted.fit_transform(df["readmitted"])


In [41]:
df['diag_1'] = df['diag_1'].str.replace('E','-')
df['diag_2'] = df['diag_2'].str.replace('E','-') 
df['diag_3'] = df['diag_3'].str.replace('E','-')
df['diag_1'] = df['diag_1'].str.replace('V','-')
df['diag_2'] = df['diag_2'].str.replace('V','-')
df['diag_3'] = df['diag_3'].str.replace('V','-')

In [42]:
'V57' in df['diag_1']

False

In [65]:
def apply_condition(row):
    if '250' in row['diag_1'] or '250' in row['diag_2'] or '250' in row['diag_3']:
        return 1
    else:
        return 0

df['diabetes'] = df.apply(apply_condition, axis=1)

In [66]:
def apply_condition(row):
    if '360'<=row['diag_1']<='490' or  '360'<=row['diag_1']<='490' or    '360'<=row['diag_1']<='490':
        return 1
    else:
        return 0
df['Circularity_diabetes'] = df.apply(apply_condition, axis=1)
df['Circularity_diabetes'].value_counts()

0    62097
1    35955
Name: Circularity_diabetes, dtype: int64

In [67]:
df['comorbidity'] = np.where((df['diabetes'] == 0) & (df['Circularity_diabetes'] == 0), 0,
                    np.where((df['diabetes'] == 1) & (df['Circularity_diabetes'] == 0), 1,
                        np.where((df['diabetes'] == 0) & (df['Circularity_diabetes'] == 1), 2, 3)
                    )
                )

In [68]:
df.shape

(98052, 48)

# Logistic Regression

In [69]:
X = df.iloc[:,0:48]
y = df.iloc[:,-1]

In [70]:
print(X)
print("Y values")
print(y)

        encounter_id  patient_nbr  race  gender  age  time_in_hospital  \
1             149190     55629189     2       0    1                 3   
2              64410     86047875     0       0    2                 2   
3             500364     82442376     2       1    3                 2   
4              16680     42519267     2       1    4                 1   
5              35754     82637451     2       1    5                 3   
...              ...          ...   ...     ...  ...               ...   
101761     443847548    100162476     0       1    7                 3   
101762     443847782     74694222     0       0    8                 5   
101763     443854148     41088789     2       1    7                 1   
101764     443857166     31693671     2       0    8                10   
101765     443867222    175429310     2       1    7                 6   

        num_lab_procedures  num_procedures  num_medications  \
1                       59               0      

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [73]:
y_pred = model.predict(X_test)


In [74]:
from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)


Accuracy: 0.37065932384886036
Classification Report:
               precision    recall  f1-score   support

           0       0.37      1.00      0.54      7269
           1       0.00      0.00      0.00      5105
           2       0.00      0.00      0.00      5165
           3       0.00      0.00      0.00      2072

    accuracy                           0.37     19611
   macro avg       0.09      0.25      0.14     19611
weighted avg       0.14      0.37      0.20     19611



C:\anaconda\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [75]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age',
       'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses',
       'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose',
       'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton',
       'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted',
       'diabeties', 'Circularity_diabetes', 'diabetes', 'comorbidity'],
      dtype='object')

KeyError: ''

# Random Forest 


In [77]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [79]:
X = df.iloc[:,0:48]
y = df.iloc[:,-1]

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [81]:
# Create a Random Forest classifier
random_forest = RandomForestClassifier(n_estimators=20, random_state=42)

# Fit the model to the training data
random_forest.fit(X_train, y_train)


RandomForestClassifier(n_estimators=20, random_state=42)

In [82]:
y_pred = random_forest.predict(X_test)

In [84]:
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)


Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14521
           1       1.00      1.00      1.00     10299
           2       1.00      1.00      1.00     10334
           3       1.00      1.00      1.00      4067

    accuracy                           1.00     39221
   macro avg       1.00      1.00      1.00     39221
weighted avg       1.00      1.00      1.00     39221



In [85]:
confusion = confusion_matrix(y_test, y_pred)
print(confusion)

[[14521     0     0     0]
 [    0 10299     0     0]
 [    0     0 10334     0]
 [    0     0     0  4067]]


In [86]:

from sklearn.tree import DecisionTreeClassifier  # For classification

In [87]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [88]:
y_pred = model.predict(X_test)

In [89]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)
print("Confusion Matrix:\n", confusion)

Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14521
           1       1.00      1.00      1.00     10299
           2       1.00      1.00      1.00     10334
           3       1.00      1.00      1.00      4067

    accuracy                           1.00     39221
   macro avg       1.00      1.00      1.00     39221
weighted avg       1.00      1.00      1.00     39221

Confusion Matrix:
 [[14521     0     0     0]
 [    0 10299     0     0]
 [    0     0 10334     0]
 [    0     0     0  4067]]
